name: opal
description: Evaluate taxonomic profiling predictions against gold standard using CAMI OPAL
keywords:
  - taxonomic profiling
  - benchmarking
  - evaluation
  - metrics
  - CAMI
  - Bioboxes
  - quality assessment
  - performance evaluation
tools:
  - opal:
      description: |
        OPAL (Ontology-based Taxonomic Profile Analysis) is a tool for evaluating
        taxonomic profiling predictions against a gold standard. It computes multiple
        metrics including UniFrac error, L1 norm, precision/recall/F1, Jaccard index,
        Shannon diversity, and Bray-Curtis distance. Generates interactive HTML reports
        with visualizations.
      homepage: https://github.com/CAMI-challenge/OPAL
      documentation: https://github.com/CAMI-challenge/OPAL/blob/master/README.md
      tool_dev_url: https://github.com/CAMI-challenge/OPAL
      doi: "10.1038/s41592-019-0406-x"
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information and optional parameters:
        - id: Sample/comparison identifier (required)
        - labels: Comma-separated labels for prediction files (optional, defaults to filenames)
        - filter: Filter predictions by relative abundance threshold (optional, e.g., 0.01 for 1%)
        - normalize: Boolean to normalize samples (optional, default: false)
        - rank: Taxonomic rank to analyze (optional, e.g., 'species', 'genus')
  - gold_standard:
      type: file
      description: |
        Gold standard taxonomic profile in CAMI Bioboxes format containing ground truth
        taxonomic composition with TAXID, RANK, TAXPATH, TAXPATHSN, and PERCENTAGE columns.
      pattern: "*.bioboxes"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV
  - predictions:
      type: file
      description: |
        One or more prediction files from taxonomic profilers in CAMI Bioboxes format.
        Each file should contain taxonomic composition predictions with the same format
        as the gold standard (TAXID, RANK, TAXPATH, TAXPATHSN, PERCENTAGE).
      pattern: "*.bioboxes"
      ontologies:
        - edam: http://edamontology.org/format_3475 # TSV

output:
  - meta:
      type: map
      description: Groovy Map containing sample information (same as input meta)
  - results:
      type: directory
      description: |
        Output directory containing OPAL evaluation results including:
        - Interactive HTML report with performance visualizations
        - Metrics files with computed performance measures
        - Summary statistics and plots
      pattern: "*/"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@taxbencher"
maintainers:
  - "@taxbencher"
