name: "comparative_analysis"
description: Perform comparative analysis of taxonomic classifiers within a biological sample
keywords:
  - metagenomics
  - taxonomic profiling
  - benchmarking
  - comparative analysis
  - PCA
  - differential abundance
tools:
  - python:
      description: Python programming language
      homepage: https://www.python.org/
      documentation: https://docs.python.org/3/
      licence: ["PSF"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', sample_id:'sample1', labels:'sample1_kraken2,sample1_metaphlan', num_classifiers:2 ]`
  - opal_dir:
      type: directory
      description: OPAL results directory containing metrics and evaluation data
      pattern: "*/"
  - gold_standard:
      type: file
      description: Gold standard bioboxes file for differential analysis
      pattern: "*.bioboxes"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - pca_plot:
      type: file
      description: HTML file with PCA visualization of classifier performance metrics
      pattern: "*_pca.html"
  - diff_taxa:
      type: file
      description: TSV file with taxa significantly different from gold standard
      pattern: "*_diff_taxa.tsv"
  - comparison_report:
      type: file
      description: HTML report with comprehensive classifier comparison
      pattern: "*_comparison.html"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@andreassjodin"
maintainers:
  - "@andreassjodin"
