name: utils_nfcore_taxbencher_pipeline
description: Utility subworkflow for taxbencher pipeline initialization and completion
keywords:
  - utility
  - initialization
  - completion
components: []
input:
  - input:
      type: channel
      description: Pipeline input parameters and configuration
output:
  - versions:
      type: channel
      description: Channel of software versions
authors:
  - "@andreassjodin"
